### ISSUE TITLE
`bake --print` show wrong docker-bake.json when we target a group which targets groups

### ISSUE THREAD

**Issue by eitsupi** [docker/buildx#1058]
When printing a group whose target is a group, it appears that the json is printed with a target name that does not exist in the json file for the target.

For example, a hcl file like that:

```hcl
group "default" {
    targets = ["other-group"]
}

group "other-group" {
    targets = ["app"]
}

target "app" {
    dockerfile = "Dockerfile"
    tags = ["docker.io/username/app"]
}
```

```shell
$ docker buildx bake --print -f docker-bake.hcl
[+] Building 0.0s (0/0)                                                                          
{
  "group": {
    "default": {
      "targets": [
        "other-group"
      ]
    }
  },
  "target": {
    "app": {
      "context": ".",
      "dockerfile": "Dockerfile",
      "tags": [
        "docker.io/username/app"
      ]
    }
  }
}
```

The groups included in the default group must be included in the json.

**Comment by jedevc** [comment]
This behavior seems to be explicitly tested for in [bake_test.go](https://github.com/docker/buildx/blob/master/bake/bake_test.go#L1049-L1089)

@crazy-max do you know why the targets aren't recursively resolved?

**Comment by eitsupi** [comment]
Any update?

**Comment by jedevc** [comment]
Sorry for the delay :tada: 

So I discussed with @crazy-max briefly internally, and the current behavior of the group key not appearing in the output JSON is intended. As I understand, there are two possible behaviors and logic behind them:

- `--print` prints all the groups that are directly part of the name specified by the command line argument (or `default` if not specified), and also prints all the targets that are directly part of the name specified. If you want programmable use, you can invoke the command again to traverse the nested group structures of the bake file.
- `--print` prints all the groups that are recursively part of the command line argument, and all the targets that all of those groups contain. If you want programmable use, all of the data is possible to consume directly, however, it doesn't just print that target.

    One issue with printing targets recursively, is that targets and groups may have non-trivial dependencies. If we were to list all the targets, then if we used the new `target:` syntax for overriding a build context, should that dependency target be listed in the output?

However, actually, we don't do either of these at the moment :eyes: We always return the `default` group name in the JSON, even if we specify a different set of targets:

```
$ docker buildx bake --print validate
[+] Building 0.0s (0/0)                                                                                                                     
{
  "group": {
    "default": {
      "targets": [
        "lint",
        ...
```

I think we should probably fix `--print` to do either option 1 (mirror the bake structure exactly in the output) or option 2 (recursively print all data), since rewriting the group names on the fly seems (at least to me) like the wrong behavior.

**Comment by eitsupi** [comment]
Thank you for your detailed explanation.
I really like the idea of using the json output from `buildx bake --print`, so it would be great if this could be fixed.
