### ISSUE TITLE
Using build arg to determine base image

### ISSUE THREAD

**Issue by mg98** [docker/buildx#1091]
My `Dockerfile` should use a different base image when building on an `arm` CPU than on an `amd`. I can get this information from the automatically set build arg `TARGETPLATFORM`. However, it seems impossible to use it for my purposes.

Ideally, what I want is

```
RUN export IMAGE=$(sh -c 'if [[ $TARGETPLATFORM = "linux/arm64" ]]; then echo "m1img"; else echo "altimg"; fi')
FROM "$IMAGE"
```

I think that will not work for various reasons. Is there any alternative syntax that could achieve this logic?

However, I also noticed for example the build arg `$TARGETPLATFORM` is blank before `FROM` statement. And I'm wondering why Docker is behaving that way.

**Comment by jedevc** [comment]
Initial disclaimer - you *probably* don't want to do this - using different base images will result in subtly (or not so subtly) different versions of the image. If possible, you should try and use the same base image for all architectures.

Disclaimer aside, you can do something this:

```dockerfile
FROM imageA as base-arm64
FROM imageB as base-amd64
# ...repeat for as many architectures as you like

FROM base-${TARGETARCH}
```

You can't use shell expansions like this, since those exported variables will just exist inside that single `RUN` context, and aren't propagated back upwards into the build. I think something like the multiple `FROM`s though is neater, and clarifies what the intention is a lot more clearly.

**Comment by mg98** [comment]
Trust me, I wouldn't do it if I did not have to. But you solved my problem. Thank you so much!!! 😍
