### ISSUE TITLE
Support for linux/arm/v8?

### ISSUE THREAD

**Issue by tmm1** [docker/buildx#127]
First of all, the new multi-arch support in docker is amazing and the QEMU integration into Docker Desktop is a real life-saver!

I work with a huge variety of ARM machines all the way from armv5l to aarch64. We have a number of devices running armv8l. Is there any chance this could be added as a supported target (i.e. `linux/arm/v8`)?

**Comment by tonistiigi** [comment]
As far as buildx is concerned the platform is mostly just a string. The problem is that I don't think you will find many base images.

If you have a dockerfile like
```
from scratch
add rootfs.tar /
```
you can already build it with `--platform=linux/arm/v8` and the resulting image or manifest list will have the variant set properly. But if your base image is `v7` your image will be `v7` as well.

For qemu support, afaik there is only one version of qemu-arm-user

**Comment by tmm1** [comment]
Thanks for the clarification.

I see there's a list of officially supported architectures on https://github.com/docker-library/official-images#architectures-other-than-amd64, but others are possible and just need base images to exist.
