### ISSUE TITLE
Feature Request: warn log wrong usage of chmod/chown in RUN command

### ISSUE THREAD

**Issue by ebuildy** [docker/buildx#1367]
In our company, I see always:

```
 RUN chown -R www-data:www-data /usr/local/apache2/htdocs
```

Which is a correct syntax, but a very bad practice. I have sent to them articles such as https://medium.com/@lmakarov/the-backlash-of-chmod-chown-mv-in-your-dockerfile-f12fe08c0b55 but I am wondering **if ``builx`` could display log warnings when bad practices is detected?**

**Comment by jedevc** [comment]
We don't parse the contents of the shell commands anywhere in buildx/buildkit, so without adding a lot of shell parsing logic, there's no easy way to detect this kind of behaviour :cry: We're also probably not going to add that, since it would add *a lot* of complexity (tl;dr: shell parsing is hard).

This kind of thing is probably better suited for a Dockerfile linter, though we don't have an official one at the moment.

**Comment by ebuildy** [comment]
You are right, this is better work for a linter.
