### ISSUE TITLE
HCL interpolation support

### ISSUE THREAD

**Issue by FernandoMiguel** [docker/buildx#148]
error: 
`Error: invalid tag "docker.pkg.github.com/fernandomiguel/buildkit/php:release-${LLB}-${GITHUB_SHA}-${INVOCATION_ID}": invalid reference format`

```hcl
group "default" {
	targets = ["php73", "nginx-base"]
}

target "cache" {
  cache-to = ["type=inline"]
}

target "php73" {
	inherits = ["cache"],
	tags = [
		"docker.pkg.github.com/fernandomiguel/buildkit/php:release-${LLB}-${GITHUB_SHA}-${INVOCATION_ID}",
		"fernandomiguel/php:/php:release-${LLB}-${GITHUB_SHA}-${INVOCATION_ID}"
	]
}
```

**Comment by tonistiigi** [comment]
Probably should do it with https://github.com/hashicorp/hcl2

**Comment by aloysbaillet** [comment]
Hi Tonis,
It would be great to move to hcl2 so that we can use expressions and variables indeed. I currently have to duplicate large amount of hcl files with very small variations that could be handled much more nicely by HCL2's string interpolation features.
I would also expect that arbitrary variables could be set from the command line via `buildx bake` command.
Thank you!
