### ISSUE TITLE
--progress=json

### ISSUE THREAD

**Issue by shykes** [docker/buildx#178]
It would be awesome if `buildx <bake|build>` supported `--progress=raw`, which would output a json stream with all the structured status information, to pipe into custom progress display helpers without having to patch `buildx` itself.

My understanding based on Tibor's explanation is that the internal plumbing is already in place for accessing the structured status info, it's just that right now it requires linking against buildkit itself.

**Comment by tiborvass** [comment]
Shouldn’t be too difficult, all that’s needed is something like a NewJSONPrinter instead of NewPrinter https://github.com/docker/buildx/blob/master/util/progress/printer.go#L33 that would in a goroutine loop and read from the `statusCh` and json encode it to `out`.

As far as UI is concerned, I think `--progress=json` would be more appropriate, if it's doing JSON encoding allowing in the future to have various encodings that could qualify as "raw".

**Comment by shykes** [comment]
I agree `--progress=json` is better. Thanks.

**Comment by thaJeztah** [comment]
👌 this would help with https://github.com/docker/compose/pull/6584#issuecomment-512791633 as well, where I suggested to have the raw info, so that the output could be made to match the old docker-compose output if needed

**Comment by camerondurham** [comment]
Is this issue still supposed to be open and could I work on a PR? Looking at the file history of `printer.go` it looks like (possibly new) modes had been added/refactored into the file [here](https://github.com/docker/buildx/blob/00cb53d0efc5e1865232df434af4434c0c87a43b/util/progress/printer.go#L15-L18) since the original comment from tiborvass ([permalink to NewPrinter function#L33](https://github.com/docker/buildx/blob/f8e8f17f4ed2bb22619c9ad84d5a636e8f36ecc9/util/progress/printer.go#L33)).

The `json` output in this issue could also be useful to me to possibly help debug some build failures in CI. If it's already implemented, I'd be interested in knowing how to use it. If it's not already implemented, I'd like to work on a PR to learn how output works. Thanks!

**Comment by sajdakabir** [comment]
Is this issue still open?

**Comment by jsternberg** [comment]
Closing this due to moby/buildkit#4113. The name is `rawjson` for the flag to leave open a possibility for a structured json output in the future.
