### ISSUE TITLE
Documentation: multiple tags by simply using multiple --tag parameters

### ISSUE THREAD

**Issue by jonstelly** [docker/buildx#396]
I had cobbled together a build process using buildx where I ran `buildx build ... --push` twice (with different tags) so I could build and publish for multiple tags.

```
docker buildx build . --platform=linux/arm64,linux/amd64 --tag my/image:0.1 --pull --push --no-cache
docker buildx build . --platform=linux/arm64,linux/amd64 --tag my/image:latest
```

It didn't immediately jump out at me that the `--tag` parameter could be specified multiple times until I happened to see `stringArray` as the type for the `--tag` parameter.  This lets me build and push to multiple tags in one step:

```
docker buildx build . --platform=linux/arm64,linux/amd64 --tag my/image:0.1 --tag my/image:latest --pull --push --no-cache
```

I'll try and find a minute to add this to the README.md and submit a PR in the next couple days but wanted to capture this as an issue to explain it first.

**Comment by timorkal** [comment]
Please +1

**Comment by yywing** [comment]
Is it work?  My test is not work.
https://github.com/docker/buildx/issues/459

**Comment by ksurl** [comment]
does this work for different registries in the same command? e.g. tag and push to docker hub and github container registry

`docker buildx build . --platform=linux/amd64 -t user/image -t ghcr.io/user/image --push`

**Comment by immanuelfodor** [comment]
Yes, it does, I'm actively using it in my CI to publish to an internal registry and DockerHub simultaneously: https://github.com/immanuelfodor/kube-karp/blob/master/.drone.yml#L59

**Comment by crazy-max** [comment]
https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#options

**Comment by dudicoco** [comment]
@crazy-max according to the docs `--tag` accepts a stringArray, however when attempting to pass multiple tags the following error occures:
```sh
$ docker buildx build -t latest,test
error: "docker buildx build" requires exactly 1 argument.
```

It seems that currently it is only possible to pass multiple `-t` arguments for each tag, even though the docs state otherwise.

Can you please explain this behaviour?

**Comment by crazy-max** [comment]
@dudicoco 

> `$ docker buildx build -t latest,test`

You need to specify the context and also [`stringArray` stores values as multiple flags](https://github.com/spf13/pflag/blob/d5e0c0615acee7028e1e2740a11102313be88de1/string_array.go#L75-L77) compared to a [`stringSlice` which takes comma-separated values](https://github.com/spf13/pflag/blob/d5e0c0615acee7028e1e2740a11102313be88de1/string_slice.go#L97-L103):

```
$ docker buildx build -t latest -t test .
```

**Comment by jonstelly** [comment]
PR might help clarify the difference?

**Comment by dudicoco** [comment]
Thanks @crazy-max, the context was missed during copy paste.

So i've encountered another issue with passing tags to the `bake` command when working with a `docker-compose.yaml` file.
Since the compose file does not allow to specify multiple tags per service, how can we specify multiple tags without using a `docker-bake.json/hcl` file?
Passing the tags via flags is not a good option as each target might use different docker repository, for example:

```yaml
services:
  app1:
    image: ${DOCKER_REGISTRY:-default}/app1:${TAG:-latest}
    build: app1/
  app2:
    image: ${DOCKER_REGISTRY:-default}/app2:${TAG:-latest}
    build: app2/
```
