### ISSUE TITLE
Usage of  cache-from or cache-to be shared across multiple processes

### ISSUE THREAD

**Issue by sashas-anyvision** [docker/buildx#421]
Hi, i am planning to use buildx cache to share docker image stages across several ci nodes. For that i am planning to put this directory on shared filesystem and access it concurrenly. 
My question is whether it supports simultaneous writes to the same root folder  issued from several docker instances. ?

**Comment by tonistiigi** [comment]
If you are asking about `--cache-to type=local` then my understanding is that it supports concurrent access but doesn't support NFS atm due to some file locking trouble. https://github.com/moby/buildkit/issues/1373

If you are asking about starting 2 instances with the same internal state directory then this is not supported.
