### ISSUE TITLE
identify push errors

### ISSUE THREAD

**Issue by errordeveloper** [docker/buildx#454]
Any HTTP 500 errors, along with DNS resolution, connection timeout can be retried, especially in CI context. A specific return code would be most handy in my use-case. If push retries could be considered in scope for buildx, that would be nice, but I'm happy to implement it in the [higher-level tool](https://github.com/errordeveloper/imagine) I've been working on. I just wish to see at least a return code, avoid having to parse the output.

**Comment by MaitreDede** [comment]
Hi,
I would also be pleased to have informations in logs, and  configurable timeouts for push operations...

**Comment by errordeveloper** [comment]
Logs already have error messages, for my use that is actually insufficient,
as I need to automate retries.

**Comment by MaitreDede** [comment]
With the latest build stack I have written (multi-arch using some raspberry pi), I am stuck at final steps.

I am launching `docker buildx build ... --push` using 3 builders (one for earch arch : amd64 arm32v7 arm64). The tag points to an insecure registry with only http exposed. The registry is configured with a config.toml :

```toml
debug = true
insecure-entitlements = [ "security.insecure" ]

[registry."my-registry"]
  http = true
  insecure = true
  mirrors = ["http://my-registry/"]
```

"Pushing layers" takes long time (3min),  but "exporting to image" is stuck (33min and still counting). I don't know what is the problem, and I don't know how I can activate more logging to diagnose when the problem is...

**Comment by errordeveloper** [comment]
@MaitreDede this sounds like a separate issue, my issue above is about making push errors easier to identify, e.g. when registry throws a 500 or connection times out.

**Comment by errordeveloper** [comment]
@tonistiigi @tiborvass @thaJeztah any thought on this?

**Comment by tonistiigi** [comment]
Push and pull network errors trigger automatic retry since buildkit v0.8

**Comment by errordeveloper** [comment]
> Push and pull network errors trigger automatic retry since buildkit v0.8

Thanks @tonistiigi, this is great news! I'll have a look sometime soon.
